### ISSUE TITLE
triton  is string

### ISSUE THREAD

**Issue by Maybe1297** [Orange-OpenSource/marine-detect#6]
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
  0%|                                                                                                                                                                                             | 0/3 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/media/zwh/yx/marine-detect-main/inference.py", line 4, in <module>
    predict_on_images(
  File "/media/zwh/yx/marine-detect-main/src/marine_detect/predict.py", line 123, in predict_on_images
    results = model(
  File "/home/a/miniconda3/envs/yolo_fish/lib/python3.10/site-packages/ultralytics/engine/model.py", line 101, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/a/miniconda3/envs/yolo_fish/lib/python3.10/site-packages/ultralytics/engine/model.py", line 235, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/a/miniconda3/envs/yolo_fish/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 311, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/home/a/miniconda3/envs/yolo_fish/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/a/miniconda3/envs/yolo_fish/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 97, in __init__
    fp16 &= pt or jit or onnx or xml or engine or nn_module or triton  # FP16
TypeError: unsupported operand type(s) for &=: 'bool' and 'str'

**Comment by dpaspont** [comment]
We have retested the environment set up  and code and did not run into issues on our side. If the issue persists after following the steps set up int the readme, please provide more information so we can recreate the problem.
